version: "3.3"
services:
    mongodb:
      image: mongo:latest
      expose:
        - '27017'
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=testing
      volumes:
        - mongodb_data:/data/db
      ports:
        - '27017:27017'
    
    users_service:
      build:
        context: users-service
      image: cloudcomp/users_service
      ports:
        - "1337:1337"
      depends_on:
        - mongodb

volumes:
  mongodb_data: {}